### ISSUE TITLE
Plugin Installer

### ISSUE THREAD

**Issue by jeaboswell** [ccarney16/pterodactyl-containers#156]
I was thinking about working on adding a section to entrypoint.sh that would check for the existence of an "install_plugins.sh" file and if it exists, run it on startup.  This way a separate image won't need to be maintained just for plugins.  Before I started work on that, I wanted to gauge the interest here.  Is this something that would be acceptable, or no?

**Comment by ccarney16** [comment]
At the moment it is something I do not and will not support for the images I publish. All plugins for pterodactyl are actually hot patches and as such, directly modify the panel code and function. Due to the unforeseen nature of this, "plugins" can and will be able to overwrite each other and may cause unforeseen problems when updating to newer versions of the panel. I will add support for plugins/modules only when Pterodactyl supports doing so without needing direct modifications to the core code.
