### ISSUE TITLE
How to upgrade from v0.7.19 to v1.0.1?

### ISSUE THREAD

**Issue by TekExplorer** [ccarney16/pterodactyl-containers#69]
Is it possible to upgrade existing v0.7.18 setups to v1.0? If so, how would one go about doing this?

**Comment by ccarney16** [comment]
I have not gotten around to migration docs. The panel should be easy to migrate over, its the daemon that is going to be interesting to work on.

**Comment by TekExplorer** [comment]
Ah, cool. Feel free to mention here whenever you get that sorted. Also I just realized that this is issue #69 lol. 69_noice.mp4

**Comment by TekExplorer** [comment]
Any info on this?

**Comment by ccarney16** [comment]
I have not gotten around to migration docs, however conversion to v1 should be simple, at least for the panel. Due to changes within the project structure, I highly recommend making a backup of your entire deployment configuration in event something does get messed up. `./data` has been pushed into `data/panel` and `db` has been pushed into `data/db`. For configuration, all environment variables have been split into `conf.d/panel.env` and `conf.d/mysql.env`, and what variables go where can be seen in the quickstart guide. Let's Encrypt has also seen changes by being moved into `conf.d/letsencrypt`. Beyond those directory changes, Pterodactyl should be able to upgrade per usual with a artisan migration.

**For the Daemon**
Since the daemon for pterodactyl moved from nodejs to golang, along with where the daemon places its data/config, there have been many changes. Conversion to the new daemon may not be straight forward. When redeploying the project with the daemon, I do recommend using the `--daemon-dir` (This may be changed in a future release) argument within `bin/deploy` and point to the current server directory (nodejs daemon used `/srv/daemon-data`), copy the newly generated config from the panel into `conf.d/daemon/` as `config.yml`. You should be able to start up the new daemon when all this is set.

**Comment by ccarney16** [comment]
You might want to also purge the data/cache and data/storage/framework before migrating, since those may cause errors when issuing a migrate command.
